services:
  - type: web
    name: vant-backend
    runtime: docker
    dockerfilePath: ./back/Dockerfile
    dockerContext: ./back
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000